exclude: ".*(.fits|.fts|.fit|.header|.txt|tca.*|extern.*|poetry.lock|tests/chains/.*)$"
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.14.8"
    hooks:
      - id: ruff
        args: ["--fix", "--unsafe-fixes"]
      - id: ruff-format
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.7
    hooks:
      - id: docformatter
        args: ["--in-place", "--pre-summary-newline", "--make-summary-multi"]
  - repo: https://github.com/PyCQA/isort
    rev: 7.0.0
    hooks:
      - id: isort
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.7.4
    hooks:
      - id: prettier
  - repo: https://github.com/hadolint/hadolint
    rev: v2.14.0
    hooks:
      - id: hadolint-docker
        entry: hadolint/hadolint:v2.12.1-beta hadolint
  - repo: https://github.com/hadolint/hadolint
    rev: v2.14.0
    hooks:
      - id: hadolint-docker
        name: Lint *.dockerfile Dockerfiles
        entry: hadolint/hadolint:v2.12.1-beta hadolint
        types: [file]
        files: \.dockerfile$
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: ["-d {extends: relaxed, rules: {line-length: disable}}", "-s"]
        files: \.(yaml|yml)$
  - repo: https://github.com/openstack/bashate
    rev: 2.1.1
    hooks:
      - id: bashate
        args: ["--ignore=E006"]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
        args: ["-x"]
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.20.0
    hooks:
      - id: markdownlint-cli2
        args: ["--format", "--fix"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: trailing-whitespace
      - id: check-yaml
      - id: debug-statements
      - id: check-added-large-files
        args: ["--enforce-all", "--maxkb=1054"]
      - id: end-of-file-fixer
      - id: mixed-line-ending
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: ["--write-changes"]
ci:
  autofix_prs: false
  autoupdate_schedule: "quarterly"
  skip: [hadolint-docker]
