# Builder stage
FROM python:3.10.9-alpine as builder

RUN apk update && \
    apk add --no-cache \
    make \
    chromium \
    chromium-chromedriver \
    harfbuzz \
    nss \
    freetype \
    ttf-freefont \
    g++ \
    libffi-dev \
    alpine-sdk \
    ncurses \
    coreutils \
    tesseract-ocr \
    tesseract-ocr-dev \
    swig

ENV PYTHONFAULTHANDLER=1 \
  PYTHONUNBUFFERED=1 \
  PYTHONDONTWRITEBYTECODE=1 \
  PYTHONHASHSEED=random \
  PIP_NO_CACHE_DIR=off \
  PIP_DISABLE_PIP_VERSION_CHECK=on \
  PIP_DEFAULT_TIMEOUT=100 \
  POETRY_VERSION=1.3.1

# System deps:
#RUN pip install "poetry==$POETRY_VERSION"

# Copy only requirements to cache them in docker layer
WORKDIR /code
#COPY poetry.lock pyproject.toml /code/
COPY requirements.txt .

# Project initialization:
#RUN poetry config virtualenvs.create false \
#  && poetry install --with scraper --no-interaction --no-ansi --no-root
RUN pip install --no-cache-dir -r requirements.txt

COPY README.md /code/
COPY Makefile /code/
COPY paper_data_linking /code/paper_data_linking

# Install the local module
#RUN poetry install

WORKDIR /code
ENV PYTHONPATH="$PYTHONPATH:./"
ENV CHROMEDRIVER_PATH="/usr/bin/chromedriver"

ENTRYPOINT ["make"]