[build-system]
requires = [
    "setuptools",
]
build-backend = "setuptools.build_meta"

[project]
name = "paper-data-linking"
version = "0.1.0"
description = "Identify and extract data references in heliophysics research papers."
authors = [
    {name = "Anthony Buonomo", email = "anthony.r.buonomo@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering",
    "Topic :: Text Processing",
]
dependencies = [
    "numpy",
    "onnxruntime",
    "openai",
    "PyMuPDF",
    "python-dotenv",
    "pydantic",
    "requests",
    "tiktoken",
    "tokenizers",
    "thefuzz",
    "langchain",
]

[project.optional-dependencies]
scrape = [
    "ads",
    "beautifulsoup4",
    "tqdm",
]
browser = [
    "selenium",
]
webapp = [
    "celery[redis]",
    "fastapi[all]",
    "flower@git+https://github.com/mher/flower.git",
    "langchain-community",
    "langchain-core",
    "langchain-openai",
    "langchain-text-splitters",
    "pdf2image",
    "pi_heif",
    "pytesseract",
    "pyyaml",
    "slowapi",
    "spacy",
    "unstructured-inference",
    "unstructured",
    "uvicorn",
]

[tool.setuptools.packages.find]
include = ["paper_data_linking*"]

[tool.setuptools.package-dir]
"" = "src"
