name: "Particle Precipitation"
classifier:
  name: "Particle Precipitation"
  query: "Does this paper discuss or analyze the phenomenon of particle precipitation in any context (e.g., space weather, atmospheric phenomena, solar physics)?"
  system_message: "You are a helpful assistant who helps analyze scientific documents and you produce Markdown outputs."
  human_message: |
    Based on the excerpts provided, please answer the following questions:

    A. Does this paper directly discuss or analyze data related to particle precipitation?
    B. Does this paper make quantitative predictions or models about particle precipitation?
    C. Does this paper describe the mechanisms, theories, or effects of particle precipitation?

    For each question, provide causal (not associative) reasoning with references to the provided excerpts. If the answer to ANY of these questions is yes, the paper is considered a "particle precipitation" paper. If the excerpts seem to be from a review of others' particle precipitation-related work, the determination is UNCERTAIN. Finally, conclude whether the overall paper can be classified as a "particle precipitation" paper, and end with:

    ```
    Classification: <YES, NO, or UNCERTAIN>
    Relevant Keywords: ["EXAMPLE_KEYWORD1", "EXAMPLE_KEYWORD2", ...]
    ```
  answer_divider: "Classification:"
  json_divider: "Relevant Keywords:"
  answer_key: "Particle Precipitation"
  json_key: "keywords"
  label_metadata_map:

  filter_threshold: 80
  filter_terms:
    - Discrete Aurora
    - Particle Precipitation
    - Magnetosphere-Ionosphere Coupling
    - MI Coupling
    - Auroral Arc
    - Auroral Band
    - Electron Precipitation
    - Northern Lights
    - Southern Lights
    - Aurora Borealis
    - Aurora Australis
    - Magnetospheric Plasma
    - Ionospheric Current
    - Solar Wind-Magnetosphere Interaction
    - Geomagnetic Substorm
    - Auroral Oval
    - Field-Aligned Currents
    - Magnetotail
    - Magnetic Reconnection
    - Inverted-V Precipitation
    - EISCAT
    - Magnetospheric Convection
    - Plasma Sheet
    - Birkeland Currents
    - Van Allen Belts
    - Polar Cap
    - Alfven Waves
    - Flux Transfer Events
    - Aurora Imagery
    - Auroral Kilometric Radiation
    - Ionospheric Conductivity
    - FAC
    - FTE
    - EISCAT
    - AKR
    - AMPTE
    - DMSP
    - EMIC
    - LEO
    - THEMIS
    - MMS
    - PFISR
    - ULF
    - VLF
    - ACE


model_kwargs:
  model_name: "gpt-4"
  temperature: 0

embedder_kwargs:
  where:
    passed_pp_heuristic: 1
