name: "Parkers Solar Probe"
classifier:
  name: "PSP"
  query: "Does this paper use data from the Parker Solar Probe spacecraft or its instruments (WISPR, WAVE, FIELDS, ISʘIS)?"
  system_message: "You are a helpful assistant who helps analyze scientific documents and you produce Markdown outputs."
  human_message: |
    Based on the excerpts provided, please answer the following questions:

    A. Does this paper directly use data from the Parker Solar Probe mission and its primary catalogues?
    B. Does this paper make quantitative predictions of results from the Parker Solar Probe mission?
    C. Does this paper describe the Parker Solar Probe mission, its instruments, operations, software, or calibrations?

    For your reference, here is a list of Parker Solar Probe instruments: WISPR, WAVE, FIELDS, ISʘIS.

    For each question, provide causal (not associative) reasoning with references to the provided excerpts (being sure to mention any Parker Solar Probe instruments used). If the answer to ANY of these questions is yes, the paper is considered a Parker Solar Probe paper. If the excerpts seem to be from a review of others' Parker Solar Probe-related work, the determination is UNCERTAIN. Finally, conclude whether the overall paper can be classified as a Parker Solar Probe paper, and end with:

    ```
    Classification: <YES, NO, or UNCERTAIN>
    PSP Instruments Used: ["EXAMPLE_INSTRUMENT1", "EXAMPLE_INSTRUMENT2", ...]
    ```
  answer_divider: "Classification:"
  json_divider: "PSP Instruments Used:"
  answer_key: "PSP"
  json_key: "instruments"
  label_metadata_map:
    WISPR:
      detail: "Wide-Field Imager for Parker Solar Probe"
      link: "https://doi.example/WISPR"
    WAVE:
      detail: "Waves"
      link: "https://doi.example/WAVE"
    FIELDS:
      detail: "Electric Field and Waves"
      link: "https://doi.example/FIELDS"
    ISʘIS:
      detail: "Integrated Science Investigation of the Sun"
      doi: "https://doi.example/ISʘIS"


  filter_threshold: 80
  filter_terms:
    - "Parker Solar Probe"
    - "WISPR"
    - "WAVE"
    - "FIELDS"
    - "ISʘIS"
    - "Wide-Field Imager for Parker Solar Probe"
    - "Waves"
    - "Electric Field and Waves"
    - "Integrated Science Investigation of the Sun"

model_kwargs:
  model_name: "gpt-4"
  temperature: 0

embedder_kwargs:
  where:
    passed_psp_heuristic: 1
