name: "Solar and Heliospheric Observatory 2"
classifier:
  name: "SOHO"
  query: "Does this paper use data from the SOHO spacecraft or its instruments (CDS, CELIAS, COSTEP, EIT, ERNE, GOLF, LASCO, MDI, SUMER, SWAN, UVCS, VIRGO)?"
  system_message: "You are a helpful assistant who helps analyze scientific documents and you produce Markdown outputs."
  human_message: | # be sure to keep this pipe as it preserves newlines in text below.
    Based on the excerpts provided, please answer the following questions:

    A. Does this paper directly use data from the SOHO mission and its primary catalogues?  
    B. Does this paper make quantitative predictions of results from the SOHO mission?  
    C. Does this paper describe the SOHO mission, its instruments, operations, software, or calibrations?

    For your reference, here is a list of SOHO instruments: CDS, CELIAS, COSTEP, EIT, ERNE, GOLF, LASCO, MDI, SUMER, SWAN, UVCS, VIRGO.

    For each question, provide causal (not associative) reasoning with references to the provided excerpts (being sure to mention any SOHO instruments used). If the answer to ANY of these questions is yes, the paper is considered a SOHO paper. If the excerpts seem to be from a review of others' SOHO-related work, the determination is UNCERTAIN. Finally, conclude whether the overall paper can be classified as a SOHO paper, and end with:

    ```
    Classification: <YES, NO, or UNCERTAIN>
    SOHO Instruments Used:
    [
      "EXAMPLE INSTRUMENT 1": {
        "time_range": "TIME RANGE 1",
        "wavelength": "WAVELENGTH1"
      },
      "EXAMPLE INSTRUMENT 2": {
        "time_range": "TIME RANGE 2",
        "wavelength": "WAVELENGTH2"
      }
    ]
    ```
  answer_divider: "Classification:"
  answer_key: "SOHO"
  json_divider: "SOHO Instruments Used:"
  json_key: "instruments"
  label_metadata_map:
    CDS:
      link: "https://doi.org/10.5270/esa-50ehv09"
      detail: "Coronal Diagnostic Spectrometer"
    CELIAS:
      link: "https://doi.org/10.5270/esa-iey8z2h"
      detail: "Charge, Element, and Isotope Analysis System"
    COSTEP:
      link: "https://doi.org/10.5270/esa-yrl3swm"
      detail: "Comprehensive Suprathermal and Energetic Particle Analyzer"
    EIT:
      link: "https://doi.org/10.5270/esa-yb6hwf9"
      detail: "Extreme ultraviolet Imaging Telescope"
    ERNE:
      link: "https://doi.org/10.5270/esa-xch97ty"
      detail: "Energetic and Relativistic Nuclei and Electron"
    GOLF:
      link: "https://doi.org/10.5270/esa-ls55aku"
      detail: "Global Oscillations at Low Frequencies"
    LASCO:
      link: "https://doi.org/10.5270/esa-4qhsiaj"
      detail: "Large Angle and Spectrometric Coronagraph"
    MDI:
      link: "https://doi.org/10.5270/esa-9kpubs2"
      detail: "Michelson Doppler Imager"
    SUMER:
      link: "https://doi.org/10.5270/esa-shl1wiw"
      detail: "Solar Ultraviolet Measurements of Emitted Radiation"
    SWAN:
      link: "https://doi.org/10.5270/esa-k1pfbpn"
      detail: "Solar Wind Anisotropies"
    UVCS:
      link: "https://doi.org/10.5270/esa-b4hhucr"
      detail: "Ultraviolet Coronagraph Spectrometer"
    VIRGO:
      link: "https://doi.org/10.5270/esa-vief1sn"
      detail: "Variability of solar IRradiance and Gravity Oscillations"

  filter_threshold: 80
  filter_terms:
      - "SOHO"
      - "CDS"
      - "CELIAS"
      - "COSTEP"
      - "EIT"
      - "ERNE"
      - "GOLF"
      - "LASCO"
      - "MDI"
      - "SUMER"
      - "SWAN"
      - "UVCS"
      - "VIRGO"
      - "Solar and Heliospheric Observatory"
      - "Coronal Diagnostic Spectrometer"
      - "Charge, Element, and Isotope Analysis System"
      - "Comprehensive Suprathermal and Energetic Particle Analyzer"
      - "Extreme ultraviolet Imaging Telescope"
      - "Energetic and Relativistic Nuclei and Electron"
      - "Global Oscillations at Low Frequencies"
      - "Large Angle and Spectrometric Coronagraph"
      - "Michelson Doppler Imager"
      - "Solar Ultraviolet Measurements of Emitted Radiation"
      - "Solar Wind Anisotropies"
      - "Ultraviolet Coronagraph Spectrometer"
      - "Variability of solar IRradiance and Gravity Oscillations"
      - "Michelson Doppler"

model_kwargs:
  model_name: "gpt-4"
  temperature: 0

embedder_kwargs:
  where:
    passed_soho_heuristic: 1
