name: "Time Range Finder"
classifier:
  name: "TimeRange"
  query: "Does this paper specify time ranges for the data sources used?"
  system_message: "You are a helpful assistant who helps analyze scientific documents and you produce Markdown outputs."
  human_message: | 
    Based on the excerpts provided, please identify:

    The time ranges mentioned in relation to the data sources used.

    Provide references to the provided excerpts for each identified time range and data source.
    Be sure to identify the date, not just the hour second and minute.
    
    Finally, conclude with:
    ```
    Found Data with Time: <YES, NO, or UNCERTAIN>
    Identified Time Ranges: [
      {
        "data_source": ["DATA SOURCE 1"],
        "time_range": ["START TIME 1", "END TIME 1"] # ISO 8601 format
      },
      {
        "data_source": ["DATA SOURCE 1"], # another entry if DATA SOURCE 1 has multiple disjoint time ranges 
        "time_range": ["START TIME 2", "END TIME 2"], 
      },
      {
        "data_source": ["DATA SOURCE 2", "DATA SOURCE 3"] # in case a fused data source is mentioned
        "time_range": ["START TIME", "END TIME"], # ISO 8601 format
      },
      ..., # More entries if needed
    ]
    ```

  answer_divider: "Found Data with Time:"
  answer_key: "Found Data with Time"
  json_divider: "Identified Time Ranges:"
  json_key: "Identified Time Ranges"
  label_metadata_map:

  filter_threshold: 80
  filter_terms:
      - "time range"
      - "frequency"
      - "data collected from"
      - "observed between"
      - "analysis period"
      - "Hz"  # This might indicate frequencies in Hertz
      - "sampled at"
      - "day"
      - "month"
      - "year"
      - "duration"
      - "spanning"
      - "interval"
      - "start date"
      - "end date"
      - "period of study"
      - "data span"
      - "measurement window"
      - "recording period"
      - "acquisition date"
      - "collection period"
      - "dataset years"
      - "data years"
      - "study years"
      - "surveyed from"
      - "monitored from"
      - "tracked from"
      - "period covered"
      - "time frame"
      - "timespan"
      - "study duration"
      - "data coverage"
      - "recorded from"
      - "sampling period"
      - "timeline"
      - "epoch"
      - "era"
      - "phase"
      - "session"
      - "study phase"
      - "measurement phase"
      - "January"
      - "February"
      - "March"
      - "April"
      - "May"
      - "June"
      - "July"
      - "August"
      - "September"
      - "October"
      - "November"
      - "December"
      - "solar cycle"
      - "solar minimum"
      - "solar maximum"


model_kwargs:
  model_name: "gpt-4"
  temperature: 0
  request_timeout: 300

embedder_kwargs:
  where:
    passed_time_frequency_heuristic: 1
