name: "Time Range and Wavelength Identifier"
classifier:
  name: "TimeWavelength"
  query: "What instruments, time ranges, and frequencies are used in this paper?"

  system_message: |
    You analyze scientific documents and produce Markdown outputs, and you help to construct sunpy queries. Here is an example working query
    ```
    from astropy import units as u

    from sunpy.net import Fido
    from sunpy.net import attrs as a

    time_range = a.Time("START TIME", "END TIME")
    search = Fido.search(time_range,
                          a.Instrument(<YOUR INSTRUMENT STR>).
                          a.Wavelength(<YOUR WAVELENGTH>*u.angstrom))  
    ```

  human_message: | 
    Based on the excerpts provided, please identify:

    A. What instruments and their respective time ranges and wavelengths that are used

    Finally, conclude with example sunpy queries and:

    ```
    Found Data with Time and Frequency: <YES, NO, or UNCERTAIN>
    Identified Frequencies: {[
      "EXAMPLE INSTRUMENT 1": {
        "time_range": "TIME RANGE 1",
        "wavelength": "WAVELENGTH1"
      },
      "EXAMPLE INSTRUMENT 2": {
        "time_range": "TIME RANGE 2",
        "wavelength": "WAVELENGTH2"
      }
    ]}
    ```

  answer_divider: "Identified Time Ranges:"
  answer_key: "TimeRanges"
  json_divider: "Identified Frequencies:"
  json_key: "Frequencies"
  label_metadata_map:

  filter_threshold: 80
  filter_terms:
      - "time range"
      - "frequency"
      - "data collected from"
      - "observed between"
      - "analysis period"
      - "Hz"  # This might indicate frequencies in Hertz
      - "sampled at"
      - "day"
      - "month"
      - "year"
      - "angstrom"
      - "nm"
      - "nanometer"

model_kwargs:
  model_name: "gpt-4"
  temperature: 0

embedder_kwargs:
  where:
    passed_time_frequency_heuristic: 1
